# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170602_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='course_count',
            new_name='courses',
        ),
    ]
