# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170517_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=32, verbose_name='\u9a8c\u8bc1\u7801'),
        ),
    ]
