/*
-- Query: SELECT * FROM mx_online.organization_courseorg
LIMIT 0, 1000

-- Date: 2017-06-01 18:44
*/
INSERT INTO `organization_courseorg` (`id`,`name`,`desc`,`click_count`,`fav_count`,`image`,`address`,`create_time`,`city_id`,`category`) VALUES (1,'慕课网','慕课网是垂直的互联网IT技能免费学习网站。以独家视频教程、在线编程工具、学习计划、问答社区为核心特色。在这里，你可以找到最好的互联网技术牛人，也可以通过免费的在线公开视频课程学习国内领先的互联网IT技术。\r\n慕课网课程涵盖前端开发、PHP、Html5、Android、iOS、Swift等IT前沿技术语言，包括基础课程、实用案例、高级分享三大类型，适合不同阶段的学习人群。以纯干货、短视频的形式为平台特点，为在校学生、职场白领提供了一个迅速提升技能、共同分享进步的学习平台。[1]',0,0,'org/2017/05/imooc.png','北京市西城区德外大街10号','2017-05-18 14:53:00.000000',2,'pxjg');
INSERT INTO `organization_courseorg` (`id`,`name`,`desc`,`click_count`,`fav_count`,`image`,`address`,`create_time`,`city_id`,`category`) VALUES (2,'慕课网 - 天津','慕课网是垂直的互联网IT技能免费学习网站。以独家视频教程、在线编程工具、学习计划、问答社区为核心特色。在这里，你可以找到最好的互联网技术牛人，也可以通过免费的在线公开视频课程学习国内领先的互联网IT技术。 慕课网课程涵盖前端开发、PHP、Html5、Android、iOS、Swift等IT前沿技术语言，包括基础课程、实用案例、高级分享三大类型，适合不同阶段的学习人群。以纯干货、短视频的形式为平台特点，为在校学生、职场白领提供了一个迅速提升技能、共同分享进步的学习平台。[1]',0,0,'org/2017/05/imooc.png','天津市西城区德外大街10号','2017-05-18 15:04:00.000000',3,'pxjg');
INSERT INTO `organization_courseorg` (`id`,`name`,`desc`,`click_count`,`fav_count`,`image`,`address`,`create_time`,`city_id`,`category`) VALUES (3,'慕课网2','慕课网是垂直的互联网IT技能免费学习网站。以独家视频教程、在线编程工具、学习计划、问答社区为核心特色。在这里，你可以找到最好的互联网技术牛人，也可以通过免费的在线公开视频课程学习国内领先的互联网IT技术。\r\n慕课网课程涵盖前端开发、PHP、Html5、Android、iOS、Swift等IT前沿技术语言，包括基础课程、实用案例、高级分享三大类型，适合不同阶段的学习人群。以纯干货、短视频的形式为平台特点，为在校学生、职场白领提供了一个迅速提升技能、共同分享进步的学习平台。[1]',0,0,'org/2017/05/imooc.png','北京市西城区德外大街10号','2017-05-18 14:53:00.000000',2,'pxjg');
INSERT INTO `organization_courseorg` (`id`,`name`,`desc`,`click_count`,`fav_count`,`image`,`address`,`create_time`,`city_id`,`category`) VALUES (4,'慕课网3','慕课网是垂直的互联网IT技能免费学习网站。以独家视频教程、在线编程工具、学习计划、问答社区为核心特色。在这里，你可以找到最好的互联网技术牛人，也可以通过免费的在线公开视频课程学习国内领先的互联网IT技术。 慕课网课程涵盖前端开发、PHP、Html5、Android、iOS、Swift等IT前沿技术语言，包括基础课程、实用案例、高级分享三大类型，适合不同阶段的学习人群。以纯干货、短视频的形式为平台特点，为在校学生、职场白领提供了一个迅速提升技能、共同分享进步的学习平台。[1]',0,0,'org/2017/05/imooc.png','天津市西城区德外大街10号','2017-05-18 15:04:00.000000',3,'pxjg');
INSERT INTO `organization_courseorg` (`id`,`name`,`desc`,`click_count`,`fav_count`,`image`,`address`,`create_time`,`city_id`,`category`) VALUES (5,'慕课网4','慕课网是垂直的互联网IT技能免费学习网站。以独家视频教程、在线编程工具、学习计划、问答社区为核心特色。在这里，你可以找到最好的互联网技术牛人，也可以通过免费的在线公开视频课程学习国内领先的互联网IT技术。 慕课网课程涵盖前端开发、PHP、Html5、Android、iOS、Swift等IT前沿技术语言，包括基础课程、实用案例、高级分享三大类型，适合不同阶段的学习人群。以纯干货、短视频的形式为平台特点，为在校学生、职场白领提供了一个迅速提升技能、共同分享进步的学习平台。[1]',0,0,'org/2017/05/imooc.png','天津市西城区德外大街10号','2017-05-18 15:04:00.000000',3,'pxjg');
INSERT INTO `organization_courseorg` (`id`,`name`,`desc`,`click_count`,`fav_count`,`image`,`address`,`create_time`,`city_id`,`category`) VALUES (6,'慕课网5','慕课网是垂直的互联网IT技能免费学习网站。以独家视频教程、在线编程工具、学习计划、问答社区为核心特色。在这里，你可以找到最好的互联网技术牛人，也可以通过免费的在线公开视频课程学习国内领先的互联网IT技术。 慕课网课程涵盖前端开发、PHP、Html5、Android、iOS、Swift等IT前沿技术语言，包括基础课程、实用案例、高级分享三大类型，适合不同阶段的学习人群。以纯干货、短视频的形式为平台特点，为在校学生、职场白领提供了一个迅速提升技能、共同分享进步的学习平台。[1]',0,0,'org/2017/05/imooc.png','天津市西城区德外大街10号','2017-05-18 15:04:00.000000',3,'pxjg');
INSERT INTO `organization_courseorg` (`id`,`name`,`desc`,`click_count`,`fav_count`,`image`,`address`,`create_time`,`city_id`,`category`) VALUES (7,'慕课网6','慕课网是垂直的互联网IT技能免费学习网站。以独家视频教程、在线编程工具、学习计划、问答社区为核心特色。在这里，你可以找到最好的互联网技术牛人，也可以通过免费的在线公开视频课程学习国内领先的互联网IT技术。 慕课网课程涵盖前端开发、PHP、Html5、Android、iOS、Swift等IT前沿技术语言，包括基础课程、实用案例、高级分享三大类型，适合不同阶段的学习人群。以纯干货、短视频的形式为平台特点，为在校学生、职场白领提供了一个迅速提升技能、共同分享进步的学习平台。[1]',0,0,'org/2017/05/imooc.png','天津市西城区德外大街10号','2017-05-18 15:04:00.000000',3,'pxjg');
INSERT INTO `organization_courseorg` (`id`,`name`,`desc`,`click_count`,`fav_count`,`image`,`address`,`create_time`,`city_id`,`category`) VALUES (8,'慕课网7','慕课网是垂直的互联网IT技能免费学习网站。以独家视频教程、在线编程工具、学习计划、问答社区为核心特色。在这里，你可以找到最好的互联网技术牛人，也可以通过免费的在线公开视频课程学习国内领先的互联网IT技术。 慕课网课程涵盖前端开发、PHP、Html5、Android、iOS、Swift等IT前沿技术语言，包括基础课程、实用案例、高级分享三大类型，适合不同阶段的学习人群。以纯干货、短视频的形式为平台特点，为在校学生、职场白领提供了一个迅速提升技能、共同分享进步的学习平台。[1]',0,0,'org/2017/05/imooc.png','天津市西城区德外大街10号','2017-05-18 15:04:00.000000',3,'pxjg');
INSERT INTO `organization_courseorg` (`id`,`name`,`desc`,`click_count`,`fav_count`,`image`,`address`,`create_time`,`city_id`,`category`) VALUES (9,'慕课网8','慕课网是垂直的互联网IT技能免费学习网站。以独家视频教程、在线编程工具、学习计划、问答社区为核心特色。在这里，你可以找到最好的互联网技术牛人，也可以通过免费的在线公开视频课程学习国内领先的互联网IT技术。 慕课网课程涵盖前端开发、PHP、Html5、Android、iOS、Swift等IT前沿技术语言，包括基础课程、实用案例、高级分享三大类型，适合不同阶段的学习人群。以纯干货、短视频的形式为平台特点，为在校学生、职场白领提供了一个迅速提升技能、共同分享进步的学习平台。[1]',0,0,'org/2017/05/imooc.png','天津市西城区德外大街10号','2017-05-18 15:04:00.000000',3,'pxjg');
